#  Marmalade - Lightweight Game Engine
#  Copyright (C) 2026 Tayler Parsons
#  Copyright (C) 2026 Ryan Bester
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

import os
import re
import glob
import shutil
import json
import argparse
import io

from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
import drawsvg as draw

from svglib.svglib import svg2rlg
from reportlab.graphics import renderPDF


def find_used_icons(sources):
    icon_regex = re.compile(r'\bICON_CI_[A-Z0-9_]+\b')
    used_icons = set()

    files = glob.glob(f'{sources}/**/*.[cpp,h]*', recursive=True)

    for file_path in files:
        try:
            with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                matches = icon_regex.findall(f.read())
                used_icons.update(matches)
        except Exception as e:
            print(f'Could not read {file_path}: {e}')
            return None

    return used_icons


def generate_mapping(font_header):
    mapping = {}
    try:
        with open(font_header, 'r', encoding='utf-8') as f:
            for line in f:
                match = re.search(
                    r'#define\s+(ICON_CI_\w+).*?U\+([0-9a-fA-F]+)', line)
                if match:
                    mapping[match.group(1)] = int(match.group(2), 16)
    except Exception as e:
        print(f'Could not read {font_header}: {e}')
        return None

    return mapping


def setup_output_dir(output_assets):
    if os.path.exists(output_assets):
        shutil.rmtree(output_assets)
    os.makedirs(f'{output_assets}')

    with open(f"{output_assets}/Contents.json", "w") as f:
        json.dump({"info": {"author": "Marmalade", "version": 1}}, f)


def load_font(font_file):
    font = TTFont(font_file)
    glyph_set = font.getGlyphSet()
    cmap = font.getBestCmap()
    return (font, glyph_set, cmap)


def icon_to_svg(mapping, font, glyph_set, cmap, icon):
    glyph_name = cmap.get(mapping[icon])
    if not glyph_name:
        print(f'Codepoint {hex(mapping[icon])} not found')
        return None

    glyph = glyph_set[glyph_name]
    pen = SVGPathPen(glyph_set)
    glyph.draw(pen)
    path_data = pen.getCommands()

    ascender = font['hhea'].ascent
    descender = font['hhea'].descent
    width = font['hmtx'][glyph_name][0]
    height = ascender - descender

    d = draw.Drawing(width, height, origin=(0, descender))

    d.append(draw.Path(d=path_data, fill='black',
                       transform=f'scale(1, -1) translate(0, {-ascender})'))

    svg_buf = d.as_svg()

    # Strip SVG header tag
    start_index = svg_buf.find('<svg')
    if start_index != -1:
        clean_svg = svg_buf[start_index:]
    else:
        clean_svg = svg_buf

    svg_io = io.StringIO(clean_svg)
    return svg_io


def svg_to_pdf(svg_io, icon, output_assets):
    drawing = svg2rlg(svg_io)

    os.makedirs(f'{output_assets}/{icon.lower()}.imageset')
    renderPDF.drawToFile(
        drawing, f'{output_assets}/{icon.lower()}.imageset/{icon.lower()}.pdf')


def write_icon_contents_json(icon, output_assets):
    contents = {
        "images": [{"filename": f'{icon.lower()}.pdf', "idiom": "universal"}],
        "info": {"author": "Marmalade", "version": 1},
        "properties": {
            "preserves-vector-representation": True,
            "template-rendering-intent": "template"
        }
    }
    with open(f'{output_assets}/{icon.lower()}.imageset/Contents.json', "w") as f:
        json.dump(contents, f, indent=4)


def bake_icons(used_icons, mapping, font, glyph_set, cmap, output_assets):
    for icon in used_icons:
        if icon in mapping:
            svg_io = icon_to_svg(mapping, font, glyph_set, cmap, icon)
            if svg_io is None:
                continue

            svg_to_pdf(svg_io, icon, output_assets)

            write_icon_contents_json(icon, output_assets)


def write_font_mapping_header(used_icons, output_header):
    with open(output_header, "w") as f:
        f.write('// Generated by bake-macos-icons.py script\n\n')
        f.write('#ifndef MARMALADE_GUI_NATIVEUI_ICONMAPPING_H\n')
        f.write('#define MARMALADE_GUI_NATIVEUI_ICONMAPPING_H\n\n')
        f.write('namespace Marmalade::GUI::NativeUI {\n\n')
        f.write(
            'static std::map<std::string, std::string> s_IconToAssetName = {\n')
        for icon_name in used_icons:
            f.write(f'    {{ {icon_name}, "{icon_name.lower()}" }},\n')
        f.write('};\n\n')
        f.write('}\n#endif\n')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--output-header', required=True)
    parser.add_argument('--output-assets', required=True)
    parser.add_argument('--sources', required=True)
    parser.add_argument('--font-file', required=True)
    parser.add_argument('--font-header', required=True)
    args = parser.parse_args()

    used_icons = find_used_icons(args.sources)
    if used_icons is None:
        return

    mapping = generate_mapping(args.font_header)
    if mapping is None:
        return

    setup_output_dir(args.output_assets)

    (font, glyph_set, cmap) = load_font(args.font_file)

    bake_icons(used_icons, mapping, font, glyph_set, cmap, args.output_assets)

    write_font_mapping_header(used_icons, args.output_header)


if __name__ == '__main__':
    main()
