#  Marmalade - Lightweight Game Engine
#  Copyright (C) 2025 Tayler Parsons
#  Copyright (C) 2025 Ryan Bester
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

# imgui-api.h
#
# Generates imgui.inc file with ImGui function calls.

import os

BASE_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
IMGUI_INC_PATH = os.path.join(BASE_PATH, 'include', 'imgui.inc')

HEADER = '''/*
 Marmalade - Lightweight Game Engine
 Copyright (C) 2025 Tayler Parsons
 Copyright (C) 2025 Ryan Bester

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
 
/*
 This file is automatically generated by the imgui-api.py script.
 */
'''

# Functions listed here in format, (function name, return type, signature, call args, [ImGui name])
# Types will need to be translated to C
FUNCTIONS = [
    ('SameLine', 'void' ,'', ''),
    ('SameLineWithOffset', 'void' ,'float offset, float spacing', 'offset, spacing', 'SameLine'),
    ('Button', 'int', 'const char *label', 'label')
]

def main():
    with open(IMGUI_INC_PATH, "w") as f:
        f.write(HEADER)
        f.write('\n')

        f.write(f"#ifdef INTERFACE_API_SIGNATURE\n")
        for name, ret_type, args, call_args, *other in FUNCTIONS:
            f.write(f"{ret_type} (*{name})({args});\n")
        f.write(f"#endif // INTERFACE_API_SIGNATURE\n\n")

        f.write(f"#ifdef INTERFACE_API_INITIALISER\n")
        for name, ret_type, args, call_args, *other in FUNCTIONS:
            f.write(f".{name} = &{name}Impl,\n")
        f.write(f"#endif // INTERFACE_API_INITIALISER\n\n")

        f.write(f"#ifdef INTERFACE_API_IMPL\n")
        for name, ret_type, args, call_args, *other in FUNCTIONS:
            imgui_func = other[0] if other else name
            f.write(f"static {ret_type} {name}Impl({args}) {{ return ImGui::{imgui_func}({call_args}); }}\n")
        f.write(f"#endif // INTERFACE_API_IMPL\n")


if __name__ == '__main__':
    main()
